import { KeyboardKey } from "./interfaces/keyboard.js";

const keyboardKeys: KeyboardKey[] = [{
    key: 'a',
    keyCode: 65,
    pianoKey: 'c2',
}, {
    key: 's',
    keyCode: 83,
    pianoKey: 'a.mp3'
}, {
    key: 'd',
    keyCode: 68,
    pianoKey: 'a.mp3'
}, {
    key: 'f',
    keyCode: 70,
    pianoKey: 'a.mp3'
}, {
    key: 'g',
    keyCode: 71,
    pianoKey: 'a.mp3'
}, {
    key: 'h',
    keyCode: 72,
    pianoKey: 'a.mp3'
}, {
    key: 'j',
    keyCode: 74,
    pianoKey: 'a.mp3'
}, {
    key: 'k',
    keyCode: 75,
    pianoKey: 'a.mp3'
}, {
    key: 'l',
    keyCode: 76,
    pianoKey: 'a.mp3'
}, {
    key: 'ç',
    keyCode: 186,
    pianoKey: 'a.mp3'
}, {
    key: ']',
    keyCode: 93,
    pianoKey: 'a.mp3'
}, {
    key: 'q',
    keyCode: 81,
    pianoKey: 'a.mp3'
}, {
    key: 'w',
    keyCode: 87,
    pianoKey: 'a.mp3'
}, {
    key: 'e',
    keyCode: 69,
    pianoKey: 'a.mp3'
}, {
    key: 'r',
    keyCode: 82,
    pianoKey: 'a.mp3'
}, {
    key: 't',
    keyCode: 84,
    pianoKey: 'a.mp3'
}, {
    key: 'y',
    keyCode: 89,
    pianoKey: 'a.mp3'
}, {
    key: 'u',
    keyCode: 85,
    pianoKey: 'a.mp3'
}, {
    key: 'i',
    keyCode: 73,
    pianoKey: 'a.mp3'
}, {
    key: 'o',
    keyCode: 79,
    pianoKey: 'a.mp3'
}, {
    key: 'p',
    keyCode: 80,
    pianoKey: 'a.mp3'
}, {
    key: '[',
    keyCode: 91,
    pianoKey: 'a.mp3'
}, {
    key: '1',
    keyCode: 49,
    pianoKey: 'a.mp3'
}, {
    key: '2',
    keyCode: 50,
    pianoKey: 'a.mp3'
}, {
    key: '3',
    keyCode: 51,
    pianoKey: 'a.mp3'
}, {
    key: '4',
    keyCode: 52,
    pianoKey: 'a.mp3'
}, {
    key: '5',
    keyCode: 53,
    pianoKey: 'a.mp3'
}, {
    key: '6',
    keyCode: 54,
    pianoKey: 'a.mp3'
}, {
    key: '7',
    keyCode: 55,
    pianoKey: 'a.mp3'
}, {
    key: '8',
    keyCode: 56,
    pianoKey: 'a.mp3'
}, {
    key: '9',
    keyCode: 57,
    pianoKey: 'a.mp3'
}, {
    key: '0',
    keyCode: 48,
    pianoKey: 'a.mp3'
}, {
    key: 'z',
    keyCode: 90,
    pianoKey: 'a.mp3'
}, {
    key: 'x',
    keyCode: 88,
    pianoKey: 'a.mp3'
}, {
    key: 'c',
    keyCode: 67,
    pianoKey: 'a.mp3'
}];

export default keyboardKeys;